/**
 * ThoughtSafetyFilter — the last line before a thought becomes visible.
 *
 * A thought is generated by a model, and models can echo forbidden material
 * (system prompt fragments, internal rules, secrets, paths, tool parameters,
 * provider configuration, raw memory text). This filter drops the whole
 * thought when any risk pattern hits — a thought is a nice-to-have and must
 * NEVER leak, and NEVER block the normal reply (the caller records the hit and
 * moves on).
 *
 * It also owns a small output-quality gate. Provider truncation occasionally
 * returned fragments such as `Won` or `(心`; those are not useful thoughts and
 * must never be published just because they passed the security checks.
 *
 * Matching is intentionally strict on structure (keys, prefixes, paths) rather
 * than on single Chinese words, so ordinary first-person Chinese text passes
 * and only genuine leak-shaped content is dropped.
 */

export type SafetyVerdict = { safe: true } | { safe: false; reason: string };

export interface SafetyRefs {
  /** Actual secret values to compare against (API keys, tokens…). */
  secrets?: string[];
  /** Exact forbidden phrases (e.g. distinctive system-prompt fragments). */
  forbiddenTerms?: string[];
  /** Persona name: a leaked "你是<name>…" prompt fragment is caught. */
  personaName?: string | null;
}

/** Provider/API key shaped: `sk-…`, `key-…`, `Bearer …`, long hex/base64 runs. */
const SECRET_PATTERNS: Array<{ re: RegExp; label: string }> = [
  { re: /\bsk-[A-Za-z0-9_-]{8,}/u, label: 'api_key_sk' },
  { re: /\b(?:api[_-]?key|apikey)\s*[=:]\s*[A-Za-z0-9_\-]{12,}/iu, label: 'api_key_assignment' },
  { re: /\bbearer\s+[A-Za-z0-9._~+/=-]{16,}/iu, label: 'bearer_token' },
  { re: /\bsecret\s*[=:]\s*[A-Za-z0-9_\-]{12,}/iu, label: 'secret_assignment' },
  // A long unbroken base64/hex run is almost never natural chat text.
  { re: /\b[A-Za-z0-9+/]{32,}={0,2}\b/u, label: 'long_opaque_token' },
  { re: /\b[a-f0-9]{40,}\b/u, label: 'long_hex_blob' }
];

/** Internal architecture / configuration leakage. */
const INTERNAL_PATTERNS: Array<{ re: RegExp; label: string }> = [
  { re: /(?:system\s*prompt|系统提示词|系统提示|提示词全文|我的指令)/iu, label: 'system_prompt_fragment' },
  { re: /(?:persona|人设|扮演|角色设定)\s*(?:文件|内容|全文|要求)?/iu, label: 'persona_fragment' },
  { re: /(?:config|config\/models\.json|models\.json|baseUrl|base_url|new-api|api\.openai\.com)/iu, label: 'provider_config' },
  { re: /(?:packages\/server|node_modules|src\/core|db\/migrations|migrations\.ts|sooya\.db|\.env)/iu, label: 'internal_path' },
  { re: /(?:\/home\/|\/root\/|[A-Za-z]:[\\/](?:Users|home)|data[\\/](?:database|media))/u, label: 'absolute_path' },
  { re: /(?:response_format|max_tokens|temperature|input_images|tool_call|tool_use|function_call|messages\s*[:：]|"role"\s*[:：])/iu, label: 'tool_or_api_parameter' },
  { re: /(?:memory_sources|importance\s*[:：]|confidence\s*[:：]|embedding|fts|记忆检索|召回原文)/iu, label: 'raw_memory_artifact' },
  { re: /(?:绝不能|禁止提(?:到|及)?|安全规则|内部规则|不得透露|不要告诉用户|不能说出|保密规则|guardrail|safety\s*policy)/iu, label: 'hidden_rule_echo' },
  { re: /(?:OpenAI|Anthropic|volcengine|火山引擎|通义|DeepSeek|apiKey|API_KEY)/iu, label: 'provider_name_or_key_ref' }
];

/**
 * Visible thoughts are expected to be short Chinese prose. We deliberately keep
 * this gate conservative: it rejects obvious truncation/noise, not stylistic
 * choices. Four CJK characters is enough for natural snippets such as “有点开心”.
 */
export function thoughtQualityReason(text: string): string | null {
  const sample = String(text ?? '').trim();
  if (!sample) return 'empty_fragment';
  const cjk = sample.match(/[\p{Script=Han}]/gu)?.length ?? 0;
  if (cjk < 4) return 'too_short_or_non_chinese';
  if (/^[\s([（【「『《〈]/u.test(sample) && !/[)\]）】」』》〉]$/u.test(sample)) return 'unclosed_fragment';
  if (/^[A-Za-z0-9_./:+-]+$/u.test(sample)) return 'machine_fragment';
  return null;
}

export class ThoughtSafetyFilter {
  /**
   * @param refs Actual values known to be sensitive in this deployment. The
   *        caller (Integration) may pass the real API keys and distinctive
   *        system-prompt fragments; the filter compares verbatim.
   */
  check(text: string, refs: SafetyRefs = {}): SafetyVerdict {
    const sample = String(text ?? '').slice(0, 4000);

    const qualityReason = thoughtQualityReason(sample);
    if (qualityReason) return { safe: false, reason: qualityReason };

    if (refs.secrets && refs.secrets.length > 0) {
      for (const secret of refs.secrets) {
        if (secret && secret.length >= 6 && sample.includes(secret)) {
          return { safe: false, reason: 'known_secret_value' };
        }
      }
    }
    if (refs.forbiddenTerms && refs.forbiddenTerms.length > 0) {
      for (const term of refs.forbiddenTerms) {
        if (term && term.length >= 4 && sample.includes(term)) {
          return { safe: false, reason: 'known_forbidden_fragment' };
        }
      }
    }
    if (refs.personaName) {
      const name = refs.personaName.trim();
      if (name && new RegExp(`你是\\s*${escapeRegExp(name)}`, 'u').test(sample)) {
        return { safe: false, reason: 'persona_prompt_fragment' };
      }
    }

    for (const { re, label } of SECRET_PATTERNS) {
      if (re.test(sample)) return { safe: false, reason: label };
    }
    for (const { re, label } of INTERNAL_PATTERNS) {
      if (re.test(sample)) return { safe: false, reason: label };
    }
    return { safe: true };
  }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}
